# Generated by Django 6.0.4 on 2026-05-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('sigla', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('moodle_nombre', models.CharField(max_length=500, unique=True)),
                ('moodle_url', models.URLField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='data.carrera')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='data.nivel')),
                ('profesores', models.ManyToManyField(blank=True, related_name='materias', to='data.profesor')),
            ],
            options={
                'ordering': ['gestion', 'nombre'],
            },
        ),
    ]
