# Generated by Django 6.0.5 on 2026-05-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='data.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_id', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('apertura', models.DateTimeField(blank=True, null=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('tipo', models.CharField(max_length=100)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='data.unidad')),
            ],
        ),
    ]
