# Generated by Django 6.0.5 on 2026-05-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_unidad_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='apertura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cierre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
