# Generated by Django 6.0.5 on 2026-05-15 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_tarea_apertura_alter_tarea_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_userid', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_mod_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_mod_calificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios_entrega', models.TextField(blank=True, null=True)),
                ('comentarios_feedback', models.TextField(blank=True, null=True)),
                ('calificacion_final', models.CharField(blank=True, max_length=100, null=True)),
                ('link_calificar', models.URLField(blank=True, max_length=1000, null=True)),
                ('archivos', models.JSONField(blank=True, default=list)),
                ('archivosurl', models.JSONField(blank=True, default=list)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='data.tarea')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='data.estudiante')),
            ],
            options={
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
