# Generated by Django 6.0.5 on 2026-05-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_estudiante_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='archivosurl',
        ),
        migrations.CreateModel(
            name='ArchivoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1500)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_tarea', to='data.tarea')),
            ],
        ),
    ]
