# Generated by Django 6.0.5 on 2026-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_profesor_moodle_session_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoExtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, default='', max_length=64)),
                ('usuario', models.CharField(blank=True, default='', max_length=255)),
                ('en_curso', models.BooleanField(default=False)),
                ('iniciado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
