# Generated by Django 6.0.5 on 2026-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_profesor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='url_entrega',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
