# Generated by Django 6.0.5 on 2026-10-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_tarea_descripcion_tarea_url_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasParciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_inicio', models.DateField(blank=True, null=True)),
                ('p1_fin', models.DateField(blank=True, null=True)),
                ('p2_inicio', models.DateField(blank=True, null=True)),
                ('p2_fin', models.DateField(blank=True, null=True)),
                ('p3_inicio', models.DateField(blank=True, null=True)),
                ('p3_fin', models.DateField(blank=True, null=True)),
                ('p4_inicio', models.DateField(blank=True, null=True)),
                ('p4_fin', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_parciales', to='data.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='PesosCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitek', models.PositiveSmallIntegerField(default=0)),
                ('etek', models.PositiveSmallIntegerField(default=0)),
                ('training', models.PositiveSmallIntegerField(default=0)),
                ('designlab', models.PositiveSmallIntegerField(default=0)),
                ('examen', models.PositiveSmallIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_categorias', to='data.profesor')),
            ],
        ),
    ]
