# Generated by Django 6.0.5 on 2026-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_fechasparciales_pesoscategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(blank=True, choices=[('mitek', 'Mi-Tek'), ('etek', 'E-Tek'), ('training', 'Training'), ('designlab', 'Design Lab'), ('examen', 'Examen')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='parcial',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
