# Generated by Django 6.0.5 on 2026-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_tarea_categoria_tarea_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='nota_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
